extends SceneTree

const World = preload("res://scripts/world.gd")
const Economy = preload("res://scripts/economy.gd")

func _init() -> void:
	var world = World.new(424242)
	var initial_wind: Array = world.wind_layers.duplicate(true)
	var economy = Economy.new(world)
	assert(world.wind_layers == initial_wind, "Initial setup must preserve seeded wind")
	assert(economy.fuel_airports.size() == 3)
	assert(economy.food_airports.size() == 3)
	assert(economy.hotel_airports.size() == 3)
	assert(economy.repair_airports.size() == 3)
	assert(economy.money == 160)
	assert(is_equal_approx(economy.fuel_price_per_l(economy.fuel_airports[0]), 1.4))
	assert(is_equal_approx(economy.fuel_price_per_l(economy.fuel_airports[1]), 2.0))
	assert(is_equal_approx(economy.fuel_price_per_l(economy.fuel_airports[2]), 2.6))
	assert(economy.food_price(economy.food_airports[0]) == 14)
	assert(economy.food_price(economy.food_airports[1]) == 20)
	assert(economy.food_price(economy.food_airports[2]) == 26)
	assert(economy.hotel_rest_price(economy.hotel_airports[0]) == 7)
	assert(economy.hotel_rest_price(economy.hotel_airports[1]) == 10)
	assert(economy.hotel_rest_price(economy.hotel_airports[2]) == 13)
	var empty_airports := 0
	for airport_index in world.airports.size():
		if economy.optional_service_count(airport_index) == 0:
			empty_airports += 1
	assert(empty_airports <= Economy.MAX_AIRPORTS_WITHOUT_OPTIONAL_SERVICES)
	assert(economy.offers_at(0).size() == 3)
	var destinations := {}
	for offer in economy.offers_at(0):
		assert(int(offer.destination) != 0)
		assert(not destinations.has(offer.destination))
		destinations[offer.destination] = true
		assert(offer.route_distance_km >= offer.direct_distance_km)
		assert(offer.distance_km == offer.route_distance_km)
		assert(offer.poverty_bonus_percent == economy.poverty_bonus_percent(offer.destination))
		var base_reward := Economy.BASE_REWARD_50_KM * pow(float(offer.route_distance_km) / 50.0, 1.12)
		assert(offer.normal_reward == roundi(base_reward * economy.poverty_reward_multiplier(offer.destination)))
		assert(offer.urgent_reward == offer.normal_reward * 2)
		assert(is_equal_approx(float(offer.urgent_deadline), -1.0))
	var parcel: Dictionary = economy.accept_offer(0, 0)
	assert(not parcel.is_empty() and parcel.urgent_deadline > economy.elapsed_seconds)
	var expected_deadline: float = economy.elapsed_seconds + float(parcel.route_distance_km) / Economy.DEADLINE_SPEED_KMH * 3600.0 + Economy.DEADLINE_RESERVE_SECONDS
	assert(is_equal_approx(parcel.urgent_deadline, expected_deadline))
	assert(economy.store_carried())
	assert(economy.take_slot(0))
	var destination := int(parcel.destination)
	var expected := int(parcel.urgent_reward)
	var delivery: Dictionary = economy.deliver_carried(destination)
	assert(delivery.urgent and delivery.paid == expected)
	var old_offers: Array = economy.offers_at(0).duplicate(true)
	economy.arrive_at_airport(0, world)
	assert(economy.offers_at(0) == old_offers)
	var initial_storms: Array = world.storms.duplicate(true)
	economy.arrive_at_airport(destination, world)
	assert(economy.offers_at(destination).size() == 3)
	assert(world.wind_layers == initial_wind and world.storms == initial_storms, "Economy arrivals must not mutate physical weather")
	for layer in world.wind_layers:
		assert(layer.speed_kmh >= 8.0 and layer.speed_kmh <= 32.0)
		assert(layer.from_deg >= 0.0 and layer.from_deg <= 360.0)
	var arrival_wind: Array = world.wind_layers.duplicate(true)
	economy.arrive_at_airport(destination, world)
	assert(world.wind_layers == arrival_wind)
	var saved_arrival = Economy.new()
	assert(saved_arrival.restore(economy.snapshot()))
	saved_arrival.arrive_at_airport(destination, world)
	assert(world.wind_layers == arrival_wind, "Restoring a save must preserve the previous-airport rule")
	economy.arrive_at_airport(0, world)
	assert(world.wind_layers == arrival_wind, "Mail offer refreshes must remain independent from weather")
	assert(economy.buy_canister())
	var fuel_money_before: int = economy.money
	assert(is_equal_approx(economy.fill_carried_canister(19.7, economy.fuel_airports[0]), 19.7))
	assert(economy.money == fuel_money_before - 28)
	assert(is_equal_approx(economy.transfer_carried_fuel(7.3, 7.9), 7.3))
	assert(is_equal_approx(economy.carried_item.fuel_l, 12.4))
	assert(is_equal_approx(economy.transfer_carried_fuel(0.1, 0.06), 0.06))
	var snapshot := economy.snapshot()
	var restored = Economy.new()
	assert(restored.restore(snapshot) and restored.snapshot() == snapshot)
	assert(is_equal_approx(restored.fuel_price_per_l(restored.fuel_airports[2]), 2.6))
	var shopper = Economy.new(world)
	var food_money_before: int = shopper.money
	assert(shopper.buy_food(shopper.food_airports[0]))
	assert(shopper.money == food_money_before - shopper.food_price(shopper.food_airports[0]))
	var needs = Economy.new(world)
	needs.advance_time(3600.0)
	assert(needs.hunger == 5 and needs.fatigue == 5)
	needs.fatigue = 1
	assert(needs.recover_aircraft_bed_unit())
	assert(needs.fatigue == 2)
	assert(not needs.recover_aircraft_bed_unit() and needs.fatigue == 2)
	var money_before_hotel: int = needs.money
	var hotel_airport: int = needs.hotel_airports[2]
	assert(needs.buy_hotel_rest(hotel_airport))
	assert(needs.fatigue == 3 and needs.money == money_before_hotel - needs.hotel_rest_price(hotel_airport))
	needs.advance_time(3600.0, true)
	assert(needs.fatigue == 3 and needs.hunger == 4)
	print("economy_test: OK")
	quit()
